builds:
  - main: ./cmd/deckhouse-status
    binary: deckhouse-status
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{ .Version }}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: binary
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

release:
  github:
    owner: glitchy-sheep
    name: deckhouse-status
